---
layout: post
title : ES6-Promise学习笔记
description: 
categories: code
author: Tim Gao
tags: [codes]
---

# 1. Promise的含义

Promise 是异步编程的一种解决方案。从语法上讲，promise是一个对象，可以获取异步操作的消息。它提供了统一的API，各种异步操作都可以以同样的方式处理。Promise对象有三种状态pending(进行中),fullfilled(已成功),rejected（已失败）。

Promise对象的2个特点

* (1) 对象的状态不受外界的影响.只有异步操作的结果可以决定当前是哪一种状态,任何其他操作都无法改变这种状态。
* (2) 一旦状态改变就永远不会变化，任何时候都可以得到这个结果。

Promise的状态改变只能有两种情况: 从pending到fullfilled或者从pending到rejected.
有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise对象提供统一的接口，使得控制异步操作更加容易

Promise的3个缺点

* (1) 无法取消Promise，一旦新建它就会立即执行，无法中途取消。

* (2) 如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。

* (3) 当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

# 2. 基本用法

    const promise = new Promise(function(resolve, reject) {
        // ... some code

        if (/* 异步操作成功 */){
            resolve(value);
        } else {
            reject(error);
        }
    });

Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。

resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从 pending 变为 resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；
reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

Promise实例生成之后，可以用**then**方法指定成功和失败的回调

    promise.then(function(value) {
    // success
    }, function(error) {
    // failure
    });

then方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为resolved时调用，第二个回调函数是Promise对象的状态变为rejected时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。

    function timeout(ms) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, ms, 'done');
    });
    }

    timeout(100).then((value) => {
    console.log(value);
    });
    //100毫秒后输出'done'

Promise 新建后就会立即执行。

    let promise = new Promise(function(resolve, reject) {
    console.log('Promise');
    resolve();
    });

    promise.then(function() {
    console.log('resolved.');
    });

    console.log('Hi!');

    // Promise
    // Hi!
    // resolved

# 3. Promise.prototype.then

then的作用是为 Promise 实例添加状态改变时的回调函数。then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数。

then返回的还是一个Promise对象，因此可以采用链式写法

    getJSON("/posts.json").then(function(json) {
        return json.post;
    }).then(function(post) {
        // ...
    });

# 4. Promise.prototype.catch

Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。

    getJSON('/posts.json').then(function(posts) {
        // ...
    }).catch(function(error) {
        // 处理 getJSON 和 前一个回调函数运行时发生的错误
        console.log('发生错误！', error);
    });

如果 Promise 状态已经变成resolved，再抛出错误是无效的。

    const promise = new Promise(function(resolve, reject) {
        resolve('ok');
        throw new Error('test');
    });
    promise
    .then(function(value) { console.log(value) })
    .catch(function(error) { console.log(error) });
    // ok

Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。

    getJSON('/post/1.json').then(function(post) {
        return getJSON(post.commentURL);
    }).then(function(comments) {
        // some code
    }).catch(function(error) {
        // 处理前面三个Promise产生的错误
    });

一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。

    // bad
    promise
    .then(function(data) {
        // success
    }, function(err) {
        // error
    });

    // good
    promise
    .then(function(data) { //cb
        // success
    })
    .catch(function(err) {
        // error
    });

# 5. Promise.prototype.finally

finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。

    promise
    .then(result => {···})
    .catch(error => {···})
    .finally(() => {···});

finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。这表明，finally方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。

# 6. Promise.all

# 7. Promise.race

# 8. Promise.resolve

# 9. Promise.reject